# Generated by Django 2.2.6 on 2020-05-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200517_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='job',
        ),
    ]
